name: Build Sukisu Ultra

on:
  workflow_dispatch:

jobs:
  build:
    name: Build Kernel for RMX3371
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y git wget build-essential bc curl flex bison libssl-dev ccache \
            libncurses-dev clang lld zip libstdc++6 p7zip-full

      - name: Clone kernel source
        run: |
          git clone -b phoeniX-SSU --depth=1 https://github.com/DinhQuangDoi/kernel_realme_RMX3371.git kernel
          cd kernel
          git submodule update --init --recursive

      - name: Clone clang toolchain
        run: |
          git clone --depth=1 https://gitlab.com/provasishh/clang tc

      - name: Build kernel
        run: |
          export KERNEL_DIR=$GITHUB_WORKSPACE/kernel
          export TC_DIR=$GITHUB_WORKSPACE/tc
          export OUT_DIR=$KERNEL_DIR/out

          cd $KERNEL_DIR
          mkdir -p out

          export ARCH=arm64
          export SUBARCH=arm64
          export CROSS_COMPILE=$TC_DIR/aarch64-linux-android-4.9/bin/aarch64-linux-android-
          export CLANG_TRIPLE=aarch64-linux-gnu-
          export PATH=$TC_DIR/clang/bin:$PATH

          make O=out vendor/kona-perf_defconfig
          make O=out -j$(nproc) \
            CC=clang \
            LLVM=1 \
            LLVM_IAS=1 \
            NM=llvm-nm \
            OBJDUMP=llvm-objdump \
            STRIP=llvm-strip \
            OBJCOPY=llvm-objcopy

      - name: Clone AnyKernel3
        run: |
          git clone --depth=1 https://github.com/bijoyv9/AnyKernel3.git anykernel

      - name: Pack AnyKernel zip
        run: |
          cp kernel/out/arch/arm64/boot/Image anykernel/
          cd anykernel
          zip -r Kernel-RMX3371.zip *
          mv Kernel-RMX3371.zip $GITHUB_WORKSPACE/

      - name: Upload zip
        uses: actions/upload-artifact@v4
        with:
          name: Kernel-RMX3371
          path: Kernel-RMX3371.zip
